### ISSUE TITLE
Crash when opening any multi-page file from the command line

### ISSUE THREAD

**Issue by eliasrg** [unruhschuh/MrWriter#26]
Thanks for this promising program! I am getting a crash when trying to open a file with more than one page from the command line. But when I open it via the "Open" dialog, it works.

I create a file "file.moj" with two blank pages (the bug also happens if there is text on the pages) and open it with "MrWriter file.moj". I get this error:

    QPixmap::setMask() mask size differs from pixmap size
    terminate called after throwing an instance of 'std::out_of_range'
      what():  vector::_M_range_check: __n (which is 1) >= this->size() (which is 1)
    zsh: abort (core dumped)  MrWriter file.moj

Compiling with debug symbols and using gdb, I get the following stack trace:

    #0  0x00007ffff6640615 in raise () at /usr/lib/libc.so.6
    #1  0x00007ffff6629862 in abort () at /usr/lib/libc.so.6
    #2  0x00007ffff69c486a in __gnu_cxx::__verbose_terminate_handler() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
    #3  0x00007ffff69d0d9a in __cxxabiv1::__terminate(void (*)()) (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
    #4  0x00007ffff69d0e07 in std::terminate() () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
    #5  0x00007ffff69d10ae in __cxxabiv1::__cxa_throw(void*, std::type_info*, void (*)(void*))
        (obj=obj@entry=0x555555bafdc0, tinfo=0x7ffff6afd268 <typeinfo for std::out_of_range>, dest=0x7ffff69e6fa0 <std::out_of_range::~out_of_range()>)
        at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
    #6  0x00007ffff69c75ed in std::__throw_out_of_range_fmt(char const*, ...) (__fmt=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/src/c++11/functexcept.cc:96
    #7  0x000055555558e71f in Widget::updateAllPageBuffers(bool) ()
    #8  0x00007ffff7a0bb0e in QWidget::event(QEvent*) () at /usr/lib/libQt5Widgets.so.5
    #9  0x00007ffff79ca752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /usr/lib/libQt5Widgets.so.5
    #10 0x00007ffff6e66cda in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
    #11 0x00007ffff7a08338 in QWidgetPrivate::show_helper() () at /usr/lib/libQt5Widgets.so.5
    #12 0x00007ffff7a0828a in QWidgetPrivate::showChildren(bool) () at /usr/lib/libQt5Widgets.so.5
    #13 0x00007ffff7a08312 in QWidgetPrivate::show_helper() () at /usr/lib/libQt5Widgets.so.5
    #14 0x00007ffff7a0b64d in QWidgetPrivate::setVisible(bool) () at /usr/lib/libQt5Widgets.so.5
    #15 0x00007ffff7a08273 in QWidgetPrivate::showChildren(bool) () at /usr/lib/libQt5Widgets.so.5
    #16 0x00007ffff7a08312 in QWidgetPrivate::show_helper() () at /usr/lib/libQt5Widgets.so.5
    #17 0x00007ffff7a0b64d in QWidgetPrivate::setVisible(bool) () at /usr/lib/libQt5Widgets.so.5
    #18 0x00007ffff7a08273 in QWidgetPrivate::showChildren(bool) () at /usr/lib/libQt5Widgets.so.5
    #19 0x00007ffff7a08312 in QWidgetPrivate::show_helper() () at /usr/lib/libQt5Widgets.so.5
    #20 0x00007ffff7a0b64d in QWidgetPrivate::setVisible(bool) () at /usr/lib/libQt5Widgets.so.5
    #21 0x000055555556d5bf in main(int, char**) (argc=<optimized out>, argv=0x7fffffffe398) at src/main.cpp:49

So something is being indexed out of range in `Widget::updateAllPageBuffers`.

The strange thing is, as I have said, that this _only_ happens if the file has more than one page, and _only_ when the file is opened directly from the command line.

**Comment by giucal** [comment]
This also happens on macOS.

<details>
<summary>Crash log when opening an (empty) two-pages file by double-clicking.</summary>

```
Process:               MrWriter [1462]
Path:                  /Applications/MrWriter.app/Contents/MacOS/MrWriter
Identifier:            com.yourcompany.MrWriter
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           MrWriter [1462]
User ID:               501

Date/Time:             2021-07-17 11:39:07.918 +0200
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        1951147B-CE78-A42D-7FD5-F9FB8570FD48

Sleep/Wake UUID:       68B5D5B6-696C-44E9-B6EF-8B3AEBCBF55B

Time Awake Since Boot: 6900 seconds
Time Since Wake:       3200 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type std::out_of_range: vector
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff2038692e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff203b55bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff2030a411 abort + 120
3   libc++abi.dylib               	0x00007fff20378ef2 abort_message + 241
4   libc++abi.dylib               	0x00007fff2036a5e5 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	0x00007fff20263595 _objc_terminate() + 104
6   libc++abi.dylib               	0x00007fff20378307 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff2037add1 __cxa_rethrow + 99
8   libobjc.A.dylib               	0x00007fff20261110 objc_exception_rethrow + 37
9   com.apple.AppKit              	0x00007fff22c9e282 -[NSApplication run] + 659
10  libqcocoa.dylib               	0x000000010638f2c4 0x106357000 + 230084
11  org.qt-project.QtCore         	0x0000000103feed97 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 439
12  org.qt-project.QtCore         	0x0000000103ff3162 QCoreApplication::exec() + 130
13  com.yourcompany.MrWriter      	0x0000000102f69a35 main + 1349
14  libdyld.dylib                 	0x00007fff203d0f5d start + 1
```
</details>

Similar outcome when using the command line, but the exception seems to arise differently.

```
% /Applications/MrWriter.app/Contents/MacOS/MrWriter Desktop/test.moj  
QPixmap::setMask() mask size differs from pixmap size
libc++abi: terminating with uncaught exception of type std::out_of_range: vector
zsh: abort      /Applications/MrWriter.app/Contents/MacOS/MrWriter Desktop/test.moj
```

<details>
<summary>Crash log when opening an (empty) two-pages file from the command line.</summary>

```
Process:               MrWriter [1543]
Path:                  /Applications/MrWriter.app/Contents/MacOS/MrWriter
Identifier:            com.yourcompany.MrWriter
Version:               0
Code Type:             X86-64 (Native)
Parent Process:        zsh [1489]
Responsible:           Terminal [1016]
User ID:               501

Date/Time:             2021-07-17 11:48:18.916 +0200
OS Version:            macOS 11.4 (20F71)
Report Version:        12
Bridge OS Version:     5.4 (18P4663)
Anonymous UUID:        1951147B-CE78-A42D-7FD5-F9FB8570FD48

Sleep/Wake UUID:       68B5D5B6-696C-44E9-B6EF-8B3AEBCBF55B

Time Awake Since Boot: 7400 seconds
Time Since Wake:       3800 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type std::out_of_range: vector
abort() called

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff2038692e __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff203b55bd pthread_kill + 263
2   libsystem_c.dylib             	0x00007fff2030a411 abort + 120
3   libc++abi.dylib               	0x00007fff20378ef2 abort_message + 241
4   libc++abi.dylib               	0x00007fff2036a5e5 demangling_terminate_handler() + 242
5   libobjc.A.dylib               	0x00007fff20263595 _objc_terminate() + 104
6   libc++abi.dylib               	0x00007fff20378307 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff2037abeb __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	0x00007fff2037abb2 __cxa_throw + 116
9   libc++.1.dylib                	0x00007fff2034dbd6 std::__1::__throw_out_of_range(char const*) + 56
10  libc++.1.dylib                	0x00007fff20356154 std::__1::__vector_base_common<true>::__throw_out_of_range() const + 16
11  com.yourcompany.MrWriter      	0x0000000101a9464d Widget::updateAllPageBuffers(bool) + 1069
12  org.qt-project.QtWidgets      	0x0000000101d8b54c QWidget::event(QEvent*) + 1164
13  org.qt-project.QtWidgets      	0x0000000101d51c76 QApplicationPrivate::notify_helper(QObject*, QEvent*) + 262
14  org.qt-project.QtWidgets      	0x0000000101d53042 QApplication::notify(QObject*, QEvent*) + 466
15  org.qt-project.QtCore         	0x0000000102af2bd4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
16  org.qt-project.QtWidgets      	0x0000000101d8a2ba QWidgetPrivate::show_helper() + 426
17  org.qt-project.QtWidgets      	0x0000000101d8a528 QWidgetPrivate::showChildren(bool) + 408
18  org.qt-project.QtWidgets      	0x0000000101d8a158 QWidgetPrivate::show_helper() + 72
19  org.qt-project.QtWidgets      	0x0000000101d8af44 QWidgetPrivate::setVisible(bool) + 868
20  org.qt-project.QtWidgets      	0x0000000101d8a51e QWidgetPrivate::showChildren(bool) + 398
21  org.qt-project.QtWidgets      	0x0000000101d8a158 QWidgetPrivate::show_helper() + 72
22  org.qt-project.QtWidgets      	0x0000000101d8af44 QWidgetPrivate::setVisible(bool) + 868
23  org.qt-project.QtWidgets      	0x0000000101d8a51e QWidgetPrivate::showChildren(bool) + 398
24  org.qt-project.QtWidgets      	0x0000000101d8a158 QWidgetPrivate::show_helper() + 72
25  org.qt-project.QtWidgets      	0x0000000101d8af44 QWidgetPrivate::setVisible(bool) + 868
26  com.yourcompany.MrWriter      	0x0000000101a66a28 main + 1336
27  libdyld.dylib                 	0x00007fff203d0f5d start + 1
```
</details>
